### PR TITLE
WIP: Optimiser

### PR DESCRIPTION
**Pull request by RobertRosca**
Adds in a way to perform centre optimisation, which is crucial for analysis involving azimuthal integration. The tutorial notebook explains it better than I can here: https://github.com/RobertRosca/geoAssembler/blob/optimiser/docs/geoOptimiser-tutorial.ipynb

Main things added are:

`Integrator` class:
 - Takes in our geometry (+ sample distance in mm) object and wraps the pyFAI functions
 - Makes it a bit cleaner/easier to set up and run the integrator
 - An identical class exists in the update of the `extra-data-interactive` widget, however as that is only on GitLab I have defined it here again. Would it be worth having something like `extra-algorithms` where we can store these small-ish snippets? Could contain things like this integrator, and known ways to mask detectors, etc...

`CentreOptimiser` class:
 - Takes in our geometry and a detector image frame (+ sample dist)
 - Creates and stores an integrator object
 - Contains the loss function, function which creates and fills in the grids, and an optimise function which runs a coarse grid search followed by progressively finer searches

And finally the tutorial notebook mentioned at the start.

Marked as WIP as there are a some things left to do:

 - [ ] Tests
 - [ ] Plotting functions
 - [ ] Convenient way to extract/save the corrected geometry
 - [ ] Maybe some warnings for users trying to use multiprocessing on login nodes?

### CODE REVIEW

**Comment by RobertRosca** [comment]
@zhujun98 if you're interested ;)

**Comment by takluyver** [comment]
> An identical class exists in the update of the extra-data-interactive widget, however as that is only on GitLab I have defined it here again. Would it be worth having something like extra-algorithms where we can store these small-ish snippets? Could contain things like this integrator, and known ways to mask detectors, etc...

Would extra-geom be the place for these things? It sounds like they're related to detector geometry, though I haven't looked at the code yet.

Thanks for summarising what each bit is meant to do.

**Comment by takluyver** [comment]
I'd suggest we refer to this as something like 'centre optimiser', rather than geoOptimiser (in the notebook), because:

- We might create other geometry optimisation features, e.g. moving all quadrants, using a different kind of pattern, or estimating detector-sample distance.
- CrystFEL already has a [geoptimiser](https://www.desy.de/~twhite/crystfel/manual-geoptimiser.html) tool, so there's potential for confusion.

**Comment by takluyver** [comment]
> If you're curious, it's possible to (relatively) quickly calculate the values over a large pixel grid, which shows that there are no false/local minima for the algorithm to get trapped into:

I think the larger grid actually shows a load of local minima - every spot that is darker than its neighbours is a local minimum. So this technique relies on knowing roughly where the centre is already - which we do.

**Comment by takluyver** [comment]
Looking at the code, I'd like to move away from assembling the image before integrating it. Assembly is relatively slow and loses precision, so ideally it's something that we do only to view images.

I believe it should be possible to reshape the un-assembled data to a 2D array (8192 x 128 for AGIPD) and give pyFAI a distortion array (from [to_distortion_array](https://extra-geom.readthedocs.io/en/latest/geometry.html#extra_geom.AGIPD_1MGeometry.to_distortion_array) describing the location of each pixel.

**Pull request closed without merging**
