### PR TITLE
Separate qt & notebook subpackages

### PR DESCRIPTION
**Pull request by takluyver**
This is meant to make it easier to work on either the Qt or notebook interface, by clearly separating the code for those two things. It also means that the notebook interface should work without loading the Qt libraries - though not the other way (the Qt interface will still import the notebook code).

I also noticed while working on this that `geoAssembler --notebook` is broken in master - the code uses a `--clen` option which was never defined. This was fixed along the way.

There is a moderately large diff here, but most of the changes are simply moving code around, so hopefully it isn't too hard to review.

### CODE REVIEW

**Comment by dallanto** [comment]
Hi Thomas,
I've gone through your commits and like the clarity of the separation, starting with the subfolders for sub-packages, new file names, docstring edits etc.
The new main.py code is short and clear, and I guess the conditional import of pyQt saves resources as well.
My question: you have ``def create_nb(rundir=None, geofile=None, clen=None ...`` in nb/template.py, but you are not passing the ``clen`` kwarg  from the main.py, which is technically fine but means that there's no user option for setting this; it relies on the constant CLEN = 0.119 - unless I miss something.

**Comment by takluyver** [comment]
Thanks @dallanto! Yes, you're right, the clen option isn't passed - but that's because there's no `--clen` argument defined. And if we define it, then it's ignored by the Qt interface, so I thought that using the default for the notebook interface is the easiest way to go for now.

**Comment by dallanto** [comment]
> Thanks @dallanto! Yes, you're right, the clen option isn't passed - but that's because there's no `--clen` argument defined. And if we define it, then it's ignored by the Qt interface, so I thought that using the default for the notebook interface is the easiest way to go for now.

Allright, wasn't aware of the fact that it's ignored by Qt.

Looking into the code also reminded my of the string.replace() method, in a general context, and that there's pathlib (which I didn't know before) as alternative to os.path 

Overall: LGTM

**Comment by takluyver** [comment]
Thanks. :-) Yes, pathlib is pretty nice - though it gets messy in some situations if you end up converting between `Path` objects and strings a lot. It's better with recent versions of Python, as most file functions now accept a `Path` object directly.

**Pull request merged**
